id: I44AF723A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:20:48+00:00'
last_modified: '2022-06-09T04:09:05.952164+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16606
  title: སྔ་འགྱུར་རྙིང་མའི་ལུགས་ཀྱི་ལྟ་སྒོམ་སྤྱོད་གསུམ་གྱི་རྣམ་གཞག་མདོ་རྩམ་བརྗོད་པ་ཚེས་པའི་ཟླ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6CE6:
      image_group_id: I1KG16631
      title: Volume 1 of snga 'gyur rnying ma'i lugs kyi lta sgom spyod gsum gyi rnam
        gzhag mdo rtsam brjod pa tshes pa'i zla ba/
      total_pages: 434
      order: 1
      base_file: 6CE6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
