id: P008081
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16606
  title: སྔ་འགྱུར་རྙིང་མའི་ལུགས་ཀྱི་ལྟ་སྒོམ་སྤྱོད་གསུམ་གྱི་རྣམ་གཞག་མདོ་རྩམ་བརྗོད་པ་ཚེས་པའི་ཟླ་བ།
  author: ''
  volumes:
    1f9901019ba747ae8a982c39b40e6990:
      image_group_id: I1KG16631
      title: ''
      volume_number: 1
      total_pages: 434
ebook_metadata:
  title: སྔ་འགྱུར་རྙིང་མའི་ལུགས་ཀྱི་ལྟ་སྒོམ་སྤྱོད་གསུམ་གྱི་རྣམ་གཞག་མདོ་རྩམ་བརྗོད་པ་ཚེས་པའི་ཟླ་བ།
  author: ''
  sku: P008081
  cover: cover.jpg
  layers:
  - pagination
