id: opecha:P008081
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16606
  title: སྔ་འགྱུར་རྙིང་མའི་ལུགས་ཀྱི་ལྟ་སྒོམ་སྤྱོད་གསུམ་གྱི་རྣམ་གཞག་མདོ་རྩམ་བརྗོད་པ་ཚེས་པའི་ཟླ་བ།
  volume: ''
  author: ''
